"""add_legal_reasoning_engine

Revision ID: 038d9051d549
Revises: d928f94a00fe
Create Date: 2026-07-02 09:49:26.562725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038d9051d549'
down_revision: Union[str, None] = 'd928f94a00fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contradiction_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contradiction_reports_case_id'), 'contradiction_reports', ['case_id'], unique=False)
    op.create_table('evidence_rankings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('rankings_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_rankings_case_id'), 'evidence_rankings', ['case_id'], unique=False)
    op.create_table('qa_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('strategy', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_breakdown_json', sa.Text(), nullable=True),
    sa.Column('reasoning_steps_json', sa.Text(), nullable=True),
    sa.Column('citations_json', sa.Text(), nullable=True),
    sa.Column('validation_json', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_history_case_id'), 'qa_history', ['case_id'], unique=False)
    op.create_index(op.f('ix_qa_history_user_id'), 'qa_history', ['user_id'], unique=False)
    op.create_table('research_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('bookmarks_json', sa.Text(), nullable=True),
    sa.Column('search_history_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_sessions_case_id'), 'research_sessions', ['case_id'], unique=False)
    op.create_index(op.f('ix_research_sessions_user_id'), 'research_sessions', ['user_id'], unique=False)
    op.create_table('reasoning_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('qa_id', sa.UUID(), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['qa_id'], ['qa_history.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reasoning_metrics_qa_id'), 'reasoning_metrics', ['qa_id'], unique=False)
    op.create_table('research_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_notes_session_id'), 'research_notes', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_notes_session_id'), table_name='research_notes')
    op.drop_table('research_notes')
    op.drop_index(op.f('ix_reasoning_metrics_qa_id'), table_name='reasoning_metrics')
    op.drop_table('reasoning_metrics')
    op.drop_index(op.f('ix_research_sessions_user_id'), table_name='research_sessions')
    op.drop_index(op.f('ix_research_sessions_case_id'), table_name='research_sessions')
    op.drop_table('research_sessions')
    op.drop_index(op.f('ix_qa_history_user_id'), table_name='qa_history')
    op.drop_index(op.f('ix_qa_history_case_id'), table_name='qa_history')
    op.drop_table('qa_history')
    op.drop_index(op.f('ix_evidence_rankings_case_id'), table_name='evidence_rankings')
    op.drop_table('evidence_rankings')
    op.drop_index(op.f('ix_contradiction_reports_case_id'), table_name='contradiction_reports')
    op.drop_table('contradiction_reports')
    # ### end Alembic commands ###
