"""add_qdrant_sync_infrastructure

Revision ID: 212adff733bf
Revises: 2178a6b8c63a
Create Date: 2026-07-01 12:24:07.827214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '212adff733bf'
down_revision: Union[str, None] = '2178a6b8c63a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute("ALTER TYPE jobtype ADD VALUE IF NOT EXISTS 'vector_sync'")
    op.execute("BEGIN")
    op.create_table('vector_sync_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'queued', 'starting', 'running', 'completed', 'failed', 'cancelled', name='jobstatus', create_type=False), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vector_sync_jobs_document_id'), 'vector_sync_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_vector_sync_jobs_status'), 'vector_sync_jobs', ['status'], unique=False)
    op.add_column('document_embeddings', sa.Column('is_synced', sa.Boolean(), nullable=False))
    op.add_column('document_embeddings', sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_document_embeddings_is_synced'), 'document_embeddings', ['is_synced'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_embeddings_is_synced'), table_name='document_embeddings')
    op.drop_column('document_embeddings', 'synced_at')
    op.drop_column('document_embeddings', 'is_synced')
    op.drop_index(op.f('ix_vector_sync_jobs_status'), table_name='vector_sync_jobs')
    op.drop_index(op.f('ix_vector_sync_jobs_document_id'), table_name='vector_sync_jobs')
    op.drop_table('vector_sync_jobs')
    # ### end Alembic commands ###
