"""add_embedding_infrastructure

Revision ID: 2178a6b8c63a
Revises: 23eb6d30389d
Create Date: 2026-07-01 11:57:29.804986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2178a6b8c63a'
down_revision: Union[str, None] = '23eb6d30389d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'queued', 'starting', 'running', 'completed', 'failed', 'cancelled', name='jobstatus', create_type=False), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_jobs_document_id'), 'embedding_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_embedding_jobs_status'), 'embedding_jobs', ['status'], unique=False)
    op.create_table('document_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('embedding_vector', sa.JSON(), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(length=255), nullable=False),
    sa.Column('embedding_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_embeddings_chunk_id'), 'document_embeddings', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_document_embeddings_document_id'), 'document_embeddings', ['document_id'], unique=False)
    op.drop_index('ix_cases_owner_archived', table_name='cases')
    op.create_index(op.f('ix_cases_archived'), 'cases', ['archived'], unique=False)
    op.create_index(op.f('ix_cases_owner_id'), 'cases', ['owner_id'], unique=False)
    op.drop_constraint('document_texts_document_id_key', 'document_texts', type_='unique')
    op.drop_index('ix_document_texts_document_id', table_name='document_texts')
    op.create_index(op.f('ix_document_texts_document_id'), 'document_texts', ['document_id'], unique=True)
    # Create the new enum type before altering the column type
    sa.Enum('created', 'queued', 'started', 'progress', 'retry', 'cancelled', 'completed', 'failed', 'info', name='joblogeventtype').create(op.get_bind())
    op.alter_column('processing_job_logs', 'event_type',
               existing_type=postgresql.ENUM('created', 'queued', 'started', 'progress', 'retry', 'cancelled', 'completed', 'failed', 'info', name='joblogenventtype'),
               type_=sa.Enum('created', 'queued', 'started', 'progress', 'retry', 'cancelled', 'completed', 'failed', 'info', name='joblogeventtype'),
               existing_nullable=False,
               postgresql_using="event_type::text::joblogeventtype")
    op.drop_index('ix_processing_jobs_document_type_status', table_name='processing_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_processing_jobs_document_type_status', 'processing_jobs', ['document_id', 'job_type', 'status'], unique=False)
    op.alter_column('processing_job_logs', 'event_type',
               existing_type=sa.Enum('created', 'queued', 'started', 'progress', 'retry', 'cancelled', 'completed', 'failed', 'info', name='joblogeventtype'),
               type_=postgresql.ENUM('created', 'queued', 'started', 'progress', 'retry', 'cancelled', 'completed', 'failed', 'info', name='joblogenventtype'),
               existing_nullable=False,
               postgresql_using="event_type::text::joblogenventtype")
    sa.Enum('created', 'queued', 'started', 'progress', 'retry', 'cancelled', 'completed', 'failed', 'info', name='joblogeventtype').drop(op.get_bind())
    op.drop_index(op.f('ix_document_texts_document_id'), table_name='document_texts')
    op.create_index('ix_document_texts_document_id', 'document_texts', ['document_id'], unique=False)
    op.create_unique_constraint('document_texts_document_id_key', 'document_texts', ['document_id'])
    op.drop_index(op.f('ix_cases_owner_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_archived'), table_name='cases')
    op.create_index('ix_cases_owner_archived', 'cases', ['owner_id', 'archived'], unique=False)
    op.drop_index(op.f('ix_document_embeddings_document_id'), table_name='document_embeddings')
    op.drop_index(op.f('ix_document_embeddings_chunk_id'), table_name='document_embeddings')
    op.drop_table('document_embeddings')
    op.drop_index(op.f('ix_embedding_jobs_status'), table_name='embedding_jobs')
    op.drop_index(op.f('ix_embedding_jobs_document_id'), table_name='embedding_jobs')
    op.drop_table('embedding_jobs')
    # ### end Alembic commands ###
