"""add_retrieval_logs_table

Revision ID: 4a4850d3a0c9
Revises: 212adff733bf
Create Date: 2026-07-01 12:51:09.999459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a4850d3a0c9'
down_revision: Union[str, None] = '212adff733bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retrieval_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('filters_json', sa.Text(), nullable=True),
    sa.Column('retrieved_documents_json', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('top_score', sa.Float(), nullable=False),
    sa.Column('chunks_returned', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieval_logs_created_at'), 'retrieval_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_retrieval_logs_user_id'), 'retrieval_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retrieval_logs_user_id'), table_name='retrieval_logs')
    op.drop_index(op.f('ix_retrieval_logs_created_at'), table_name='retrieval_logs')
    op.drop_table('retrieval_logs')
    # ### end Alembic commands ###
