"""upgrade_chat_messages_table_for_rag

Revision ID: 55e9919e0d83
Revises: 4a4850d3a0c9
Create Date: 2026-07-01 14:16:39.495626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e9919e0d83'
down_revision: Union[str, None] = '4a4850d3a0c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('citations_json', sa.Text(), nullable=True))
    op.add_column('chat_messages', sa.Column('token_usage_json', sa.Text(), nullable=True))
    op.add_column('chat_messages', sa.Column('latency_ms', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'latency_ms')
    op.drop_column('chat_messages', 'token_usage_json')
    op.drop_column('chat_messages', 'citations_json')
    # ### end Alembic commands ###
