"""upgrade_timeline_events

Revision ID: b261acc21224
Revises: 2b9f5d9d94af
Create Date: 2026-07-01 17:02:57.948627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b261acc21224'
down_revision: Union[str, None] = '2b9f5d9d94af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_event_id', sa.UUID(), nullable=False),
    sa.Column('child_event_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['child_event_id'], ['timeline_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_event_id'], ['timeline_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_relationships_child_event_id'), 'event_relationships', ['child_event_id'], unique=False)
    op.create_index(op.f('ix_event_relationships_parent_event_id'), 'event_relationships', ['parent_event_id'], unique=False)
    op.add_column('timeline_events', sa.Column('event_title', sa.String(length=200), nullable=True))
    op.add_column('timeline_events', sa.Column('event_description', sa.Text(), nullable=True))
    op.add_column('timeline_events', sa.Column('normalized_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('timeline_events', sa.Column('original_date', sa.String(length=100), nullable=True))
    op.add_column('timeline_events', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('timeline_events', sa.Column('chunk_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_timeline_events_normalized_date'), 'timeline_events', ['normalized_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_events_normalized_date'), table_name='timeline_events')
    op.drop_column('timeline_events', 'chunk_id')
    op.drop_column('timeline_events', 'page_number')
    op.drop_column('timeline_events', 'original_date')
    op.drop_column('timeline_events', 'normalized_date')
    op.drop_column('timeline_events', 'event_description')
    op.drop_column('timeline_events', 'event_title')
    op.drop_index(op.f('ix_event_relationships_parent_event_id'), table_name='event_relationships')
    op.drop_index(op.f('ix_event_relationships_child_event_id'), table_name='event_relationships')
    op.drop_table('event_relationships')
    # ### end Alembic commands ###
