"""add_analytics_snapshots_table

Revision ID: c11ae3d8cad0
Revises: cd7e5aebf893
Create Date: 2026-07-01 21:55:42.922426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c11ae3d8cad0'
down_revision: Union[str, None] = 'cd7e5aebf893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_type', sa.String(length=50), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_snapshots_case_id'), 'analytics_snapshots', ['case_id'], unique=False)
    op.create_index(op.f('ix_analytics_snapshots_created_at'), 'analytics_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_analytics_snapshots_snapshot_type'), 'analytics_snapshots', ['snapshot_type'], unique=False)
    op.create_index(op.f('ix_analytics_snapshots_updated_at'), 'analytics_snapshots', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_snapshots_updated_at'), table_name='analytics_snapshots')
    op.drop_index(op.f('ix_analytics_snapshots_snapshot_type'), table_name='analytics_snapshots')
    op.drop_index(op.f('ix_analytics_snapshots_created_at'), table_name='analytics_snapshots')
    op.drop_index(op.f('ix_analytics_snapshots_case_id'), table_name='analytics_snapshots')
    op.drop_table('analytics_snapshots')
    # ### end Alembic commands ###
