"""extend_case_intelligence_enterprise

Revision ID: cd7e5aebf893
Revises: ff4d9ed18ef3
Create Date: 2026-07-01 20:11:57.813606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd7e5aebf893'
down_revision: Union[str, None] = 'ff4d9ed18ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acts_statutes', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.add_column('acts_statutes', sa.Column('aliases', sa.String(length=500), nullable=True))
    op.add_column('acts_statutes', sa.Column('confidence_breakdown', sa.Text(), nullable=True))
    op.create_index(op.f('ix_acts_statutes_parent_id'), 'acts_statutes', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'acts_statutes', 'acts_statutes', ['parent_id'], ['id'], ondelete='SET NULL')
    op.add_column('claims_defenses', sa.Column('confidence_breakdown', sa.Text(), nullable=True))
    op.add_column('entity_relationships', sa.Column('reasoning_metadata', sa.Text(), nullable=True))
    op.add_column('entity_relationships', sa.Column('source_doc_id', sa.UUID(), nullable=True))
    op.add_column('entity_relationships', sa.Column('confidence_breakdown', sa.Text(), nullable=True))
    op.create_index(op.f('ix_entity_relationships_source_doc_id'), 'entity_relationships', ['source_doc_id'], unique=False)
    op.create_foreign_key(None, 'entity_relationships', 'documents', ['source_doc_id'], ['id'], ondelete='SET NULL')
    op.add_column('legal_entities', sa.Column('canonical_id', sa.UUID(), nullable=True))
    op.add_column('legal_entities', sa.Column('resolution_status', sa.String(length=50), server_default='unresolved', nullable=False))
    op.add_column('legal_entities', sa.Column('similarity_score', sa.Float(), nullable=True))
    op.add_column('legal_entities', sa.Column('merge_metadata', sa.Text(), nullable=True))
    op.add_column('legal_entities', sa.Column('confidence_breakdown', sa.Text(), nullable=True))
    op.create_index(op.f('ix_legal_entities_canonical_id'), 'legal_entities', ['canonical_id'], unique=False)
    op.create_foreign_key(None, 'legal_entities', 'legal_entities', ['canonical_id'], ['id'], ondelete='SET NULL')
    op.add_column('legal_evidence', sa.Column('strength_score', sa.Float(), server_default='0.5', nullable=False))
    op.add_column('legal_evidence', sa.Column('confidence_breakdown', sa.Text(), nullable=True))
    op.add_column('legal_facts', sa.Column('category', sa.String(length=50), server_default='Factual Findings', nullable=False))
    op.add_column('legal_facts', sa.Column('importance_score', sa.Float(), server_default='0.5', nullable=False))
    op.add_column('legal_facts', sa.Column('processing_version', sa.String(length=20), server_default='1.0.0', nullable=False))
    op.add_column('legal_facts', sa.Column('supporting_citations', sa.Text(), nullable=True))
    op.add_column('legal_facts', sa.Column('confidence_breakdown', sa.Text(), nullable=True))
    op.add_column('legal_issues', sa.Column('labels', sa.Text(), nullable=True))
    op.add_column('legal_issues', sa.Column('confidence_breakdown', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legal_issues', 'confidence_breakdown')
    op.drop_column('legal_issues', 'labels')
    op.drop_column('legal_facts', 'confidence_breakdown')
    op.drop_column('legal_facts', 'supporting_citations')
    op.drop_column('legal_facts', 'processing_version')
    op.drop_column('legal_facts', 'importance_score')
    op.drop_column('legal_facts', 'category')
    op.drop_column('legal_evidence', 'confidence_breakdown')
    op.drop_column('legal_evidence', 'strength_score')
    op.drop_constraint(None, 'legal_entities', type_='foreignkey')
    op.drop_index(op.f('ix_legal_entities_canonical_id'), table_name='legal_entities')
    op.drop_column('legal_entities', 'confidence_breakdown')
    op.drop_column('legal_entities', 'merge_metadata')
    op.drop_column('legal_entities', 'similarity_score')
    op.drop_column('legal_entities', 'resolution_status')
    op.drop_column('legal_entities', 'canonical_id')
    op.drop_constraint(None, 'entity_relationships', type_='foreignkey')
    op.drop_index(op.f('ix_entity_relationships_source_doc_id'), table_name='entity_relationships')
    op.drop_column('entity_relationships', 'confidence_breakdown')
    op.drop_column('entity_relationships', 'source_doc_id')
    op.drop_column('entity_relationships', 'reasoning_metadata')
    op.drop_column('claims_defenses', 'confidence_breakdown')
    op.drop_constraint(None, 'acts_statutes', type_='foreignkey')
    op.drop_index(op.f('ix_acts_statutes_parent_id'), table_name='acts_statutes')
    op.drop_column('acts_statutes', 'confidence_breakdown')
    op.drop_column('acts_statutes', 'aliases')
    op.drop_column('acts_statutes', 'parent_id')
    # ### end Alembic commands ###
