"""add_summarization_infrastructure

Revision ID: d928f94a00fe
Revises: c11ae3d8cad0
Create Date: 2026-07-01 22:12:31.259909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd928f94a00fe'
down_revision: Union[str, None] = 'c11ae3d8cad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('summary_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summaries_case_id'), 'summaries', ['case_id'], unique=False)
    op.create_index(op.f('ix_summaries_summary_type'), 'summaries', ['summary_type'], unique=False)
    from sqlalchemy.dialects import postgresql
    op.create_table('summary_generation_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('summary_type', sa.String(length=50), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'queued', 'starting', 'running', 'completed', 'failed', 'cancelled', name='jobstatus', create_type=False), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summary_generation_jobs_case_id'), 'summary_generation_jobs', ['case_id'], unique=False)
    op.create_index(op.f('ix_summary_generation_jobs_status'), 'summary_generation_jobs', ['status'], unique=False)
    op.create_table('summary_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('citation_coverage', sa.Float(), nullable=False),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('token_usage_json', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['summaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summary_versions_is_active'), 'summary_versions', ['is_active'], unique=False)
    op.create_index(op.f('ix_summary_versions_summary_id'), 'summary_versions', ['summary_id'], unique=False)
    op.create_table('summary_caches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('summary_type', sa.String(length=50), nullable=False),
    sa.Column('inputs_hash', sa.String(length=64), nullable=False),
    sa.Column('summary_version_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['summary_version_id'], ['summary_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summary_caches_case_id'), 'summary_caches', ['case_id'], unique=False)
    op.create_index(op.f('ix_summary_caches_inputs_hash'), 'summary_caches', ['inputs_hash'], unique=False)
    op.create_index(op.f('ix_summary_caches_summary_type'), 'summary_caches', ['summary_type'], unique=False)
    op.create_table('summary_citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('summary_version_id', sa.UUID(), nullable=False),
    sa.Column('citation_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_title', sa.String(length=255), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('citation_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['summary_version_id'], ['summary_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summary_citations_summary_version_id'), 'summary_citations', ['summary_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summary_citations_summary_version_id'), table_name='summary_citations')
    op.drop_table('summary_citations')
    op.drop_index(op.f('ix_summary_caches_summary_type'), table_name='summary_caches')
    op.drop_index(op.f('ix_summary_caches_inputs_hash'), table_name='summary_caches')
    op.drop_index(op.f('ix_summary_caches_case_id'), table_name='summary_caches')
    op.drop_table('summary_caches')
    op.drop_index(op.f('ix_summary_versions_summary_id'), table_name='summary_versions')
    op.drop_index(op.f('ix_summary_versions_is_active'), table_name='summary_versions')
    op.drop_table('summary_versions')
    op.drop_index(op.f('ix_summary_generation_jobs_status'), table_name='summary_generation_jobs')
    op.drop_index(op.f('ix_summary_generation_jobs_case_id'), table_name='summary_generation_jobs')
    op.drop_table('summary_generation_jobs')
    op.drop_index(op.f('ix_summaries_summary_type'), table_name='summaries')
    op.drop_index(op.f('ix_summaries_case_id'), table_name='summaries')
    op.drop_table('summaries')
    # ### end Alembic commands ###
