"""add_case_intelligence_tables

Revision ID: ff4d9ed18ef3
Revises: b261acc21224
Create Date: 2026-07-01 19:38:34.687668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff4d9ed18ef3'
down_revision: Union[str, None] = 'b261acc21224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_relationships_case_id'), 'entity_relationships', ['case_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_source_id'), 'entity_relationships', ['source_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_target_id'), 'entity_relationships', ['target_id'], unique=False)
    op.create_table('acts_statutes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('act_name', sa.String(length=255), nullable=False),
    sa.Column('section_reference', sa.String(length=100), nullable=True),
    sa.Column('normalized_reference', sa.String(length=255), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acts_statutes_case_id'), 'acts_statutes', ['case_id'], unique=False)
    op.create_index(op.f('ix_acts_statutes_document_id'), 'acts_statutes', ['document_id'], unique=False)
    op.create_table('claims_defenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_defenses_case_id'), 'claims_defenses', ['case_id'], unique=False)
    op.create_index(op.f('ix_claims_defenses_document_id'), 'claims_defenses', ['document_id'], unique=False)
    op.create_index(op.f('ix_claims_defenses_type'), 'claims_defenses', ['type'], unique=False)
    op.create_table('legal_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_entities_case_id'), 'legal_entities', ['case_id'], unique=False)
    op.create_index(op.f('ix_legal_entities_document_id'), 'legal_entities', ['document_id'], unique=False)
    op.create_index(op.f('ix_legal_entities_entity_type'), 'legal_entities', ['entity_type'], unique=False)
    op.create_table('legal_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_evidence_case_id'), 'legal_evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_legal_evidence_document_id'), 'legal_evidence', ['document_id'], unique=False)
    op.create_table('legal_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('chunk_id', sa.String(length=100), nullable=True),
    sa.Column('fact_text', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('citation_source', sa.String(length=255), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_facts_case_id'), 'legal_facts', ['case_id'], unique=False)
    op.create_index(op.f('ix_legal_facts_document_id'), 'legal_facts', ['document_id'], unique=False)
    op.create_table('legal_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('issue_text', sa.Text(), nullable=False),
    sa.Column('issue_category', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_issues_case_id'), 'legal_issues', ['case_id'], unique=False)
    op.create_index(op.f('ix_legal_issues_document_id'), 'legal_issues', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legal_issues_document_id'), table_name='legal_issues')
    op.drop_index(op.f('ix_legal_issues_case_id'), table_name='legal_issues')
    op.drop_table('legal_issues')
    op.drop_index(op.f('ix_legal_facts_document_id'), table_name='legal_facts')
    op.drop_index(op.f('ix_legal_facts_case_id'), table_name='legal_facts')
    op.drop_table('legal_facts')
    op.drop_index(op.f('ix_legal_evidence_document_id'), table_name='legal_evidence')
    op.drop_index(op.f('ix_legal_evidence_case_id'), table_name='legal_evidence')
    op.drop_table('legal_evidence')
    op.drop_index(op.f('ix_legal_entities_entity_type'), table_name='legal_entities')
    op.drop_index(op.f('ix_legal_entities_document_id'), table_name='legal_entities')
    op.drop_index(op.f('ix_legal_entities_case_id'), table_name='legal_entities')
    op.drop_table('legal_entities')
    op.drop_index(op.f('ix_claims_defenses_type'), table_name='claims_defenses')
    op.drop_index(op.f('ix_claims_defenses_document_id'), table_name='claims_defenses')
    op.drop_index(op.f('ix_claims_defenses_case_id'), table_name='claims_defenses')
    op.drop_table('claims_defenses')
    op.drop_index(op.f('ix_acts_statutes_document_id'), table_name='acts_statutes')
    op.drop_index(op.f('ix_acts_statutes_case_id'), table_name='acts_statutes')
    op.drop_table('acts_statutes')
    op.drop_index(op.f('ix_entity_relationships_target_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_source_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_case_id'), table_name='entity_relationships')
    op.drop_table('entity_relationships')
    # ### end Alembic commands ###
